'use strict';
const paths={today:'M3 5h18v16H3z M7 3v4 M17 3v4 M3 10h18 M7 14h3 M14 14h3 M7 18h3',units:'M4 3h16v18H4z M8 7h8 M8 12h8 M8 17h5',blocks:'M3 21V8h8v13 M11 21V3h10v18 M6 12h2 M6 16h2 M15 7h2 M15 11h2 M15 15h2 M2 21h20',survey:'M9 4H5v17h14V4h-4 M9 3h6v4H9z M8 14l3 3 5-6',photos:'M3 5h18v16H3z M3 17l5-5 4 4 3-3 6 6 M15 9h.01',issues:'M12 3L2 21h20z M12 9v5 M12 17h.01',reports:'M4 3h12l4 4v14H4z M8 16v-4 M12 16V9 M16 16v-6',bell:'M5 16h14l-2-3V9a5 5 0 0 0-10 0v4z M10 20h4',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14 M15 15l6 6',call:'M7 3H3c-1 10 8 19 18 18v-4l-5-2-2 2a15 15 0 0 1-7-7l2-2z',chat:'M21 11a9 9 0 0 1-13 8l-5 2 1-5A9 9 0 1 1 21 11 M8 10h8 M8 14h5',edit:'M14 5l5 5 M3 21l5-1L21 7l-4-4L4 16z',plus:'M12 5v14 M5 12h14',upload:'M12 16V3 M7 8l5-5 5 5 M3 16v5h18v-5',alert:'M12 3L2 21h20z M12 9v5 M12 17h.01'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.today}"/></svg>`;
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ranges=[[564,569],[544,550],[531,536],[557,562],[537,543],[551,556]],slots=['9am – 11am','11am – 1pm','2pm – 4pm','4pm – 6pm'],starts=['09:00','11:00','14:00','16:00'],ends=['11:00','13:00','16:00','18:00'];
const statusNames={A:'Completed',C:'Confirmed',D:'Opt-out',NR:'No response'};
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Singapore',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
let state={route:'today',zone:0,date:today,query:'',photoFilter:'All'};
let records=[
{id:1,block:531,unit:'05-322',name:'Sample resident 01',team:1,slot:0,status:'A',completed:today,note:'Inside / outside photos pending'},
{id:2,block:552,unit:'05-085',name:'Sample resident 02',team:2,slot:0,status:'A',completed:today,note:'Work completed · photo review'},
{id:3,block:544,unit:'02-114',name:'Sample resident 03',team:1,slot:1,status:'C',note:'Confirm access before arrival'},
{id:4,block:553,unit:'02-115',name:'Sample resident 04',team:2,slot:1,status:'C',note:'Owner available at the unit'},
{id:5,block:537,unit:'03-320',name:'Sample resident 05',team:1,slot:2,status:'C',note:'Check DB readiness'},
{id:6,block:557,unit:'10-117',name:'Sample resident 06',team:2,slot:2,status:'C',note:'Allow the full two-hour slot'},
{id:7,block:564,unit:'13-087',name:'Sample resident 07',team:1,slot:3,status:'C',note:'Long view photos required'},
{id:8,block:569,unit:'05-125',name:'Sample resident 08',team:2,slot:3,status:'C',note:'Call before arrival'},
{id:9,block:535,unit:'04-310',name:'Sample resident 09',team:null,slot:null,status:'NR',note:'Follow up with resident'},
{id:10,block:545,unit:'07-108',name:'Sample resident 10',team:null,slot:null,status:'D',note:'Collect signed opt-out form'}
].map(r=>({...r,date:today,contact:'',zone:ranges.findIndex(([a,b])=>r.block>=a&&r.block<=b)+1}));
let photos=[{id:1,record:1,stage:'After',url:'',reviewed:false},{id:2,record:2,stage:'Before',url:'',reviewed:false},{id:3,record:2,stage:'After',url:'',reviewed:false}];
let issues=[{id:1,record:5,title:'DB readiness check',note:'Confirm with the supervisor before sending the team.',owner:'Supervisor',closed:false},{id:2,record:1,title:'Completion photos pending',note:'Upload long view photographs inside and outside.',owner:'Team 1',closed:false}];
let events=[{time:'Sample activity',title:'Team 1 completed a unit',detail:'Blk 531 · #05-322 — photos pending'},{time:'Sample activity',title:'Team 2 work recorded',detail:'Blk 552 · #05-085 — ready for photo review'},{time:'Sample activity',title:'Afternoon appointments confirmed',detail:'Two teams · 2pm–4pm'}];
const navs=[['today','Dashboard'],['planner','Appointment Planner'],['photos','Photo queue'],['units','Unit register'],['blocks','Block board'],['survey','Survey visits'],['issues','Issues'],['reports','Meeting report']];
$('#navigation').innerHTML=navs.map(([id,title])=>`<button data-route="${id}" title="${title}" aria-label="${title}">${icon(id)}<span class="nav-label">${title}</span></button>`).join('');
$('#searchIcon').innerHTML=icon('search');$('#activityToggle').innerHTML=icon('bell');
$('#addAppointment').innerHTML=icon('plus')+'Appointment';$('#addPhotos').innerHTML=icon('upload')+'Photos';$('#addIssue').innerHTML=icon('issues')+'Issue';
const badge=r=>`<span class="status s-${r.status}">${r.status} · ${statusNames[r.status]}</span>`;
const filtered=()=>records.filter(r=>(!state.zone||r.zone===state.zone)&&`${r.block} ${r.unit} ${r.name} ${r.status}`.toLowerCase().includes(state.query.toLowerCase()));
const scheduled=()=>filtered().filter(r=>r.date===state.date&&r.team&&r.slot!==null&&['A','C'].includes(r.status));
const heading=(title,sub,action='')=>`<div class="page-head"><div><small class="eyebrow">PR3 / ${state.zone?'ZONE '+state.zone:'ALL SIX ZONES'}</small><h1>${title}</h1><p class="subtext">${sub}</p></div>${action}</div>`;
function render(){
 document.querySelectorAll('[data-route]').forEach(b=>{b.classList.toggle('active',b.dataset.route===state.route);b.setAttribute('aria-current',b.dataset.route===state.route?'page':'false')});
 $('#zones').innerHTML=`<button data-zone="0" class="${state.zone===0?'active':''}" aria-pressed="${state.zone===0}"><b>All zones</b><span>38 blocks</span></button>`+ranges.map(([a,b],i)=>`<button data-zone="${i+1}" class="${state.zone===i+1?'active':''}" aria-pressed="${state.zone===i+1}"><b>Zone ${i+1}</b><span>${a}–${b}</span></button>`).join('');
 document.body.dataset.route=state.route;const views={today:renderToday,planner:renderPlanner,photos:renderPhotos,units:renderUnits,blocks:renderBlocks,survey:renderSurvey,issues:renderIssues,reports:renderReports};$('#main').innerHTML=(views[state.route]||renderToday)();renderActivity();
}
function renderToday(){
 const scope=filtered(),jobs=scheduled(),count=s=>scope.filter(r=>r.status===s).length,completed=count('A'),rate=scope.length?Math.round(completed/scope.length*100):0,byZone=z=>scope.filter(r=>r.zone===z),zoneColors=['#8d55e9','#2692e6','#31ae64','#efac2f','#ee586f','#2879d4'];
 const dashHead=`<section class="dash-hero"><div class="hero-copy"><small>PR3 COMMAND CENTRE · DESIGN REHEARSAL</small><h1>ELU Upgrading – Pasir Ris</h1><p>Survey, appointments, unit status, photos and progress across all six zones.</p><div class="hero-tags"><span>▣ &nbsp; 6 Zones</span><span>▦ &nbsp; 38 Blocks</span><span>▤ &nbsp; ${scope.length} Sample Units</span></div></div><div class="hero-progress"><small>DEMO SNAPSHOT</small><div class="progress-ring" style="--p:${rate}%"><b>${rate}%</b></div><strong>${completed} / ${scope.length} sample units completed</strong></div></section>`;
 const kpis=[['A','Opt-in / Completed',completed,'#2eae6d','✓'],['C','Confirmation',count('C'),'#e44d91','▣'],['NR','No Response',count('NR'),'#e5a926','•••'],['D','Opt-out',count('D'),'#ed545f','×']];
 const metric=`<section class="dash-kpis" aria-label="Sample status counts">${kpis.map(([s,label,num,color,ic])=>`<article class="dash-kpi" style="--accent:${color}"><span class="kpi-icon">${ic}</span><div><small>${label}</small><strong>${num}</strong><span>${s} · sample records</span></div><i></i></article>`).join('')}<article class="dash-kpi" style="--accent:#197bbd"><span class="kpi-icon">▦</span><div><small>Appointments today</small><strong>${jobs.length}</strong><span>Team 1 + Team 2</span></div><i></i></article><article class="dash-kpi" style="--accent:#7455c7"><span class="kpi-icon">◎</span><div><small>Survey entries</small><strong>${scope.length}</strong><span>Sample units</span></div><i></i></article></section>`;
 const zones=`<section class="dash-card zone-panel"><header><div><small>AREA PERFORMANCE</small><h2>Zone Progress Overview</h2></div><button data-route="blocks">View all zones →</button></header><div class="zone-cards">${ranges.map(([a,b],i)=>{let rows=byZone(i+1),aCount=rows.filter(r=>r.status==='A').length,p=rows.length?Math.round(aCount/rows.length*100):0;return `<button class="zone-mini" data-zone="${i+1}" style="--zone:${zoneColors[i]}"><div><b>Zone ${i+1}</b><strong>${p}%</strong></div><span>Blk ${a}–${b}</span><i><em style="width:${p}%"></em></i><small>${aCount} / ${rows.length} sample units completed</small></button>`}).join('')}</div></section>`;
 const map=`<section class="dash-card map-panel"><header><div><small>PROJECT COVERAGE</small><h2>Project Map · 6 Zones</h2></div><button data-route="blocks">View blocks →</button></header><img src="zone-map.svg" alt="Illustrative labelled diagram of all six zone block ranges"><small class="map-note">Illustrative layout · Block numbers and zone mapping are exact</small></section>`;
 const schedule=`<section class="dash-card schedule-panel"><header><div><small>FIELD OPERATIONS</small><h2>Today’s Appointments</h2></div><div class="date-control"><button data-day="-1" aria-label="Previous day">‹</button><input id="planDate" type="date" value="${state.date}" aria-label="Schedule date"><button data-day="1" aria-label="Next day">›</button></div></header><div class="appointment-table"><div class="ap-head"><span>TIME</span><span>TEAM 1</span><span>TEAM 2</span></div>${slots.map((slot,i)=>`<div class="ap-row"><div class="ap-time"><b>${slot}</b></div>${[1,2].map(t=>{let r=jobs.find(x=>x.team===t&&x.slot===i),occupied=records.some(x=>x.date===state.date&&x.team===t&&x.slot===i&&['A','C'].includes(x.status));return r?`<article class="ap-unit"><div><strong>Blk ${r.block} · #${esc(r.unit)}</strong><small>${esc(r.name)} · Zone ${r.zone}</small></div><div class="ap-actions">${badge(r)}<button data-edit="${r.id}" title="Edit appointment" aria-label="Edit appointment for block ${r.block} unit ${esc(r.unit)}">${icon('edit')}</button></div></article>`:`<button class="ap-empty" ${occupied?'disabled':`data-new-slot="${i}" data-team="${t}"`}>${occupied?'Filtered unit':'+ Add appointment'}</button>`}).join('')}</div>`).join('')}</div></section>`;
 const ready=photos.filter(p=>p.url).length;
 const photo=`<section class="dash-card photo-panel"><header><div><small>SITE EVIDENCE</small><h2>Photo Workflow Today</h2></div><button data-route="photos">Open gallery →</button></header><div class="photo-summary"><div class="photo-meter"><span>BEFORE<br>DURING<br>AFTER</span></div><div class="photo-count"><strong>${ready}</strong><span>photos added in this session</span><strong>${photos.filter(p=>!p.reviewed).length}</strong><span>sample queue items to review</span></div></div><div class="photo-film"><div class="film-frame">${icon('photos')}</div><div class="film-frame">${icon('photos')}</div><div class="film-frame">${icon('photos')}</div><button data-upload="1">${icon('plus')}<span>Add photos</span></button></div></section>`;
 const quick=`<section class="dash-card quick-panel"><header><div><small>FIELD SHORTCUTS</small><h2>Quick Actions</h2></div></header><div class="quick-list"><button data-route="planner"><span>▣</span><b>Today’s Planner<small>Team 1 and Team 2</small></b><i>›</i></button><button data-new-appointment="1"><span>＋</span><b>New Appointment<small>Add or reschedule</small></b><i>›</i></button><button data-upload="1"><span>▧</span><b>Upload Photos<small>Before / during / after</small></b><i>›</i></button><button data-route="reports"><span>▥</span><b>Meeting Report<small>Progress and export</small></b><i>›</i></button><button data-route="issues"><span>!</span><b>Follow up Issues<small>${issues.filter(i=>!i.closed).length} open items</small></b><i>›</i></button></div></section>`;
 return `<div class="dash">${dashHead}${metric}<div class="dash-middle">${zones}${map}</div><div class="dash-bottom">${schedule}${photo}${quick}</div><p class="demo-disclosure">DESIGN PREVIEW · All people, units, counts and activities shown here are sample data. No live records are connected.</p></div>`
}
function jobCard(r){return `<article class="job ${r.status==='A'?'completed':''}"><div class="job-top"><span class="job-zone">ZONE ${r.zone} / ${r.status==='A'?'DONE':'VISIT'}</span>${badge(r)}</div><h3>Blk ${r.block} · #${esc(r.unit)}</h3><p class="job-person">${esc(r.name)}</p><div class="job-foot"><span class="job-note">${esc(r.note)}</span><div class="actions"><button class="round" data-contact="${r.id}" data-kind="call" aria-label="Call unit ${esc(r.unit)}" title="Call">${icon('call')}</button><button class="round" data-contact="${r.id}" data-kind="chat" aria-label="WhatsApp unit ${esc(r.unit)}" title="WhatsApp">${icon('chat')}</button><button class="round" data-edit="${r.id}" aria-label="Edit unit ${esc(r.unit)}" title="Edit appointment">${icon('edit')}</button></div></div></article>`}
function renderPlanner(){const jobs=scheduled();return `<div class="inner-head planner-head"><div><small class="eyebrow">FIELD SCHEDULE / TWO TEAMS</small><h1>Appointment Planner</h1><p>Four fixed slots. Check and update each team's day.</p></div><div class="planner-tools"><div class="date-control"><button data-day="-1" aria-label="Previous day">‹</button><input id="planDate" type="date" value="${state.date}" aria-label="Schedule date"><button data-day="1" aria-label="Next day">›</button></div><button class="primary" data-new-appointment="1">+ New appointment</button></div></div><div class="planner-counts"><div><b>${jobs.length}</b><span>BOOKED</span></div><div><b>${jobs.filter(x=>x.status==='C').length}</b><span>CONFIRMED · C</span></div><div><b>${jobs.filter(x=>x.status==='A').length}</b><span>COMPLETED · A</span></div><div class="planner-date-label">${esc(state.date)}<span>${state.zone?'Zone '+state.zone:'All zones'}</span></div></div><div class="planner-board"><div class="planner-lane-title"><span>TIME SLOT</span><strong>Team 1</strong><strong>Team 2</strong></div>${slots.map((s,i)=>`<div class="planner-lane"><div class="planner-time"><strong>${s}</strong><small>Slot ${i+1}</small></div>${[1,2].map(t=>{let r=jobs.find(x=>x.team===t&&x.slot===i),occupied=records.some(x=>x.date===state.date&&x.team===t&&x.slot===i&&['A','C'].includes(x.status));return r?`<article class="planner-job"><div class="planner-job-top"><span>ZONE ${r.zone} · TEAM ${t}</span>${badge(r)}</div><h3>Blk ${r.block} &nbsp; #${esc(r.unit)}</h3><p>${esc(r.name)}</p><div class="planner-job-bottom"><span>${esc(r.note)}</span><button data-edit="${r.id}">Edit / reschedule ↗</button></div></article>`:`<div class="planner-vacant">${occupied?'Unit outside current filter':`<button data-new-slot="${i}" data-team="${t}">＋ Add appointment</button>`}</div>`}).join('')}</div>`).join('')}</div><div class="planner-info">${icon('alert')} <span>Confirmed appointments use C. Mark A only after completion and enter the completion date.</span></div>`}
function renderPhotos(){const ids=filtered().map(r=>r.id),list=photos.filter(p=>ids.includes(p.record)&&(state.photoFilter==='All'||(state.photoFilter==='Reviewed'?p.reviewed:!p.reviewed)));return `<div class="inner-head photo-head"><div><small class="eyebrow">BEFORE · DURING · AFTER</small><h1>Photo Report</h1><p>Review the long-view photographs for every completed unit.</p></div><button class="primary" data-upload="1">${icon('upload')} Upload photos</button></div><div class="photo-dashboard"><div><b>${list.length}</b><span>PHOTO QUEUE ITEMS</span></div><div><b>${list.filter(p=>p.url).length}</b><span>LOCAL PREVIEWS</span></div><div><b>${list.filter(p=>p.reviewed).length}</b><span>REVIEWED</span></div><p>Choose a zone above, then inspect each unit’s Before, During and After evidence.</p></div><div class="gallery-toolbar"><div class="tabs">${['All','Needs review','Reviewed'].map(f=>`<button data-photo-filter="${f}" class="${state.photoFilter===f?'active':''}">${f}</button>`).join('')}</div><span>${list.length} items shown</span></div><div class="photo-queue">${list.map(p=>{let r=records.find(r=>r.id===p.record);return `<article class="photo-tile"><div class="photo-image">${p.url?`<img src="${p.url}" alt="${esc(p.stage)} photo for block ${r.block}, unit ${esc(r.unit)}">`:`<div class="gallery-placeholder">${icon('photos')}<strong>${esc(p.stage)}</strong><span>Photo awaiting upload</span></div>`}</div><div class="photo-info"><div class="photo-stage">${esc(p.stage)} · ZONE ${r.zone}</div><h3>Blk ${r.block} · #${esc(r.unit)}</h3><p>${p.reviewed?'Reviewed in rehearsal':p.url?'Ready for review':'No photograph attached'}</p><button class="secondary" ${p.url?`data-review="${p.id}"`:`data-upload="${r.id}"`}>${p.url?(p.reviewed?'Return to queue':'Mark reviewed'):'Attach photograph'} ↗</button></div></article>`}).join('')||'<div class="empty-state">No photos match this filter.</div>'}</div>`}
function renderUnits(){const rows=filtered();return `<div class="inner-head"><div><small class="eyebrow">MASTER UNIT VIEW</small><h1>Unit Register</h1><p>One unit record across survey, appointment and work status.</p></div><span class="readonly-pill">READ-ONLY REGISTER</span></div><div class="register-summary"><div><strong>${rows.length}</strong><span>sample units</span></div>${['A','C','D','NR'].map(k=>`<div><strong>${rows.filter(r=>r.status===k).length}</strong><span>${k} · ${statusNames[k]}</span></div>`).join('')}</div><div class="register-list"><div class="register-head"><span>UNIT / ZONE</span><span>RESIDENT</span><span>APPOINTMENT</span><span>STATUS</span><span>DETAIL</span></div>${rows.map(r=>`<article class="register-item"><div><b>Blk ${r.block} · #${esc(r.unit)}</b><small>Zone ${r.zone}</small></div><div><strong>${esc(r.name)}</strong><small>${esc(r.contact||'Contact not entered')}</small></div><div><strong>${r.team?slots[r.slot]:'—'}</strong><small>${r.team?`${esc(r.date)} · Team ${r.team}`:'No confirmed appointment'}</small></div><div>${badge(r)}</div><button data-unit="${r.id}">View unit →</button></article>`).join('')||'<div class="empty-state">No matching units.</div>'}</div>`}
function renderBlocks(){let rows=filtered(),zones=state.zone?[state.zone]:[1,2,3,4,5,6];return `<div class="inner-head"><div><small class="eyebrow">VISUAL STATUS BY BLOCK</small><h1>Block Board</h1><p>Tap a unit to open its record. Colour shows A, C, D or NR.</p></div><span class="readonly-pill">38 PROJECT BLOCKS</span></div><div class="block-key">${Object.keys(statusNames).map(k=>`<span class="status s-${k}">${k} · ${statusNames[k]}</span>`).join('')}</div><div class="block-atlas">${zones.map(z=>{let [a,b]=ranges[z-1];return `<section class="block-zone"><header><div><small>ZONE ${z}</small><h2>Blocks ${a}–${b}</h2></div><span>${rows.filter(r=>r.zone===z).length} sample units</span></header><div class="block-grid">${Array.from({length:b-a+1},(_,i)=>a+i).filter(block=>!state.query||rows.some(r=>r.block===block)).map(block=>`<article class="block-building"><header><span>BLK</span><strong>${block}</strong></header><div class="building-units">${rows.filter(r=>r.block===block).map(r=>`<button class="unit-tile s-${r.status}" data-unit="${r.id}"><b>#${esc(r.unit)}</b>${r.status}</button>`).join('')||'<span class="block-empty">No sample unit</span>'}</div></article>`).join('')||'<div class="empty-state">No blocks match.</div>'}</div></section>`}).join('')}</div>`}
function renderSurvey(){return `<div class="inner-head"><div><small class="eyebrow">FIELD VISIT NOTEBOOK</small><h1>Survey Visits</h1><p>Record owner details once, then confirm an appointment when ready.</p></div><button class="primary" data-new-survey="1">+ New survey</button></div><div class="survey-steps"><span><b>01</b> Visit unit</span><i>→</i><span><b>02</b> Record owner details</span><i>→</i><span><b>03</b> Confirm appointment</span></div><div class="survey-board">${filtered().map(r=>`<article class="survey-card"><div class="survey-card-top"><span>ZONE ${r.zone} · BLK ${r.block}</span>${badge(r)}</div><h2>#${esc(r.unit)}</h2><strong>${esc(r.name)}</strong><p>${esc(r.note)}</p><div><button data-edit="${r.id}">Update survey / appointment ↗</button></div></article>`).join('')||'<div class="empty-state">No survey entries match.</div>'}</div>`}
function renderIssues(){let ids=filtered().map(r=>r.id),visible=issues.filter(i=>ids.includes(i.record));return `<div class="inner-head"><div><small class="eyebrow">ACTION & ACCOUNTABILITY</small><h1>Issues & follow-ups</h1><p>Every issue shows the unit, responsible person and next action.</p></div><button class="primary" data-new-issue="1">+ Log issue</button></div><div class="issue-workspace"><div class="issue-list">${visible.map(i=>{let r=records.find(r=>r.id===i.record);return `<article class="issue ${i.closed?'closed':''}"><div class="issue-main"><span class="issue-label">${i.closed?'RESOLVED':'ACTION REQUIRED'} · ${esc(i.owner)}</span><h3>${esc(i.title)}</h3><p>${esc(i.note)}</p><div class="issue-bottom"><b>Blk ${r.block} · #${esc(r.unit)}</b><span>Zone ${r.zone}</span></div></div><button class="secondary" data-resolve="${i.id}">${i.closed?'Reopen':'Mark resolved'}</button></article>`}).join('')||'<div class="empty-state">No issues match this filter.</div>'}</div><aside class="issue-aside"><small>OPEN FOLLOW-UPS</small><strong>${visible.filter(i=>!i.closed).length}</strong><h2>Keep work moving.</h2><p>Check circuit breaker readiness before assigning the team. Review completion photos before closing the unit.</p><button data-route="photos">Review photo queue →</button></aside></div>`}
function renderReports(){let rows=filtered();return `<div class="inner-head"><div><small class="eyebrow">WEEKLY MEETING / SAMPLE DATA</small><h1>Meeting Report</h1><p>Clear zone comparison for the meeting. Counts reflect sample entries only.</p></div><div class="report-actions"><button class="secondary" data-print="1">Print</button><button class="primary" data-export="1">Export sample CSV ↗</button></div></div><div class="report-banner"><div><small>PROJECT SCOPE</small><h2>6 zones · 38 blocks</h2><p>Status counts update from the sample Unit Register.</p></div><div><strong>${rows.length}</strong><span>sample units in view</span></div></div><div class="report-metrics">${['A','C','D','NR'].map(k=>`<div class="report-metric s-${k}"><span>${statusNames[k]}</span><strong>${rows.filter(r=>r.status===k).length}</strong><small>${k} · sample units</small></div>`).join('')}</div><section class="report-chart"><header><small class="eyebrow">STATUS COMPARISON</small><h2>Progress by zone</h2></header>${ranges.map(([a,b],idx)=>{let r=rows.filter(x=>x.zone===idx+1),n=r.length||1;return (!state.zone||state.zone===idx+1)?`<div class="report-zone"><div><strong>Zone ${idx+1}</strong><small>Blk ${a}–${b} · ${r.length} sample units</small></div><div class="stack-bar">${['A','C','D','NR'].map(k=>`<span class="bar-${k}" style="width:${r.filter(x=>x.status===k).length/n*100}%" title="${statusNames[k]}: ${r.filter(x=>x.status===k).length}"></span>`).join('')}</div><b>${r.filter(x=>x.status==='A').length}/${r.length} A</b></div>`:''}).join('')}<div class="chart-legend">${['A','C','D','NR'].map(k=>`<span class="key-${k}">${k} · ${statusNames[k]}</span>`).join('')}</div></section>`}
function renderActivity(){const open=issues.filter(i=>!i.closed);$('#activityContent').innerHTML=(open.length?`<div class="alert-box"><div class="alert-top">${icon('alert')} ${open.length} items need attention</div><p>${esc(open[0].title)}<br>${esc(open[0].note)}</p><button class="text-action" data-route="issues">Review follow-ups ↗</button></div>`:'<div class="alert-box"><p>No open follow-ups.</p></div>')+`<div class="feed-label"><b>Workspace activity</b><span>This session</span></div><div class="feed">${events.slice(0,10).map(e=>`<div class="event"><time>${esc(e.time)}</time><p>${esc(e.title)}</p><span>${esc(e.detail)}</span></div>`).join('')}</div>`}
function log(title,detail){events.unshift({time:new Intl.DateTimeFormat('en-SG',{timeZone:'Asia/Singapore',hour:'2-digit',minute:'2-digit'}).format(new Date()),title,detail})}
let toastTimer;function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
let submitAction=null;function showDialog(title,html,fn,button='Save demo change'){submitAction=fn;$('#modalTitle').textContent=title;$('#modalFields').innerHTML=html+'<p id="formError" class="dialog-error" role="alert"></p>';$('#saveModal').textContent=button;$('#cancelModal').textContent='Cancel';$('#modal').showModal()}
const field=(name,label,value='',type='text',extra='')=>`<label class="field">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const select=(name,label,options,value)=>`<label class="field">${label}<select name="${name}">${options.map(([v,t])=>`<option value="${v}" ${String(v)===String(value)?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;
function nextFree(){for(let offset=0;offset<15;offset++){let date=new Date(state.date+'T12:00:00Z');date.setUTCDate(date.getUTCDate()+offset);let day=date.toISOString().slice(0,10);for(let i=0;i<4;i++)for(let t=1;t<=2;t++)if(!records.some(r=>r.date===day&&r.team===t&&r.slot===i&&['A','C'].includes(r.status)))return {date:day,slot:i,team:t}}return {date:state.date,slot:0,team:1}}
function editRecord(id=null,slot=0,team=1,survey=false){const r=records.find(r=>r.id===id)||{block:state.zone?ranges[state.zone-1][0]:531,unit:'',name:'',status:survey?'NR':'C',date:survey?'':state.date,team:survey?'':team,slot,note:'',completed:''};showDialog(id?'Edit unit & appointment':survey?'Add survey unit':'New appointment',`<p class="dialog-note">Rehearsal only. Saved changes update all views in this tab.</p><div class="form-row">${field('block','Block',r.block,'number','required min="531" max="569"')}${field('unit','Unit (e.g. 05-322)',r.unit,'text','required pattern="[0-9]{2}-[0-9]{2,4}"')}</div>${field('name','Owner / resident',r.name,'text','required maxlength="80"')}${field('contact','Contact (optional)',r.contact||'','tel','maxlength="30"')}<div class="form-row">${select('status','Status',Object.entries(statusNames).map(([s,n])=>[s,`${s} — ${n}`]),r.status)}${field('date','Appointment date (when confirmed)',r.date,'date')}</div><div class="form-row">${select('team','Team',[['','Unassigned'],[1,'Team 1'],[2,'Team 2']],r.team??'')}${select('slot','Time slot',slots.map((s,i)=>[i,s]),r.slot??0)}</div>${field('completed','Completion date (required for A)',r.completed||'','date')}<label class="field">Remarks<textarea name="note" maxlength="250">${esc(r.note)}</textarea></label>`,f=>{
 const block=Number(f.get('block')),unit=f.get('unit').trim(),zone=ranges.findIndex(([a,b])=>block>=a&&block<=b)+1,status=f.get('status'),newTeam=f.get('team')?Number(f.get('team')):null,newSlot=Number(f.get('slot'));
 if(!zone)throw Error('Choose a block within the six project zones.');if(records.some(x=>x.id!==id&&x.block===block&&x.unit===unit))throw Error('This unit already exists. Edit the existing record.');
 if(status==='A'&&!f.get('completed'))throw Error('Add a completion date before saving status A.');
 if(status==='C'&&!newTeam)throw Error('Choose a team for a confirmed appointment.');if(status==='C'&&!f.get('date'))throw Error('Choose an appointment date for status C.');
 if(newTeam&&['A','C'].includes(status)&&records.some(x=>x.id!==id&&x.team===newTeam&&x.slot===newSlot&&x.date===f.get('date')&&['A','C'].includes(x.status)))throw Error('This team already has a unit in that slot. Choose another slot or team.');
 const updated={...r,id:id||Date.now(),block,unit,zone,name:f.get('name').trim(),contact:f.get('contact').trim(),status,date:f.get('date'),team:['A','C'].includes(status)?newTeam:null,slot:['A','C'].includes(status)?newSlot:null,completed:status==='A'?f.get('completed'):'',note:f.get('note').trim()};
 if(id)records=records.map(x=>x.id===id?updated:x);else records.push(updated);log(id?'Unit record updated':'New unit added',`Blk ${block} · #${unit} — ${status}`);toast('Demo record saved across all views.');
 })}
function uploadPhotos(recordId){showDialog('Add site photographs',`<p class="dialog-note">Images preview locally in this tab. They are not uploaded to a server and disappear on refresh.</p>${select('record','Unit',records.map(r=>[r.id,`Blk ${r.block} · #${r.unit}`]),recordId||records[0].id)}${select('stage','Work stage',[['Before','Before'],['During','During'],['After','After']],'After')}${field('files','Select photographs','','file','required accept="image/*" multiple')}`,f=>{const files=[...$('#modalFields input[type=file]').files];if(files.some(file=>!file.type.startsWith('image/')))throw Error('Choose image files only.');files.forEach((file,i)=>{const record=Number(f.get('record')),stage=f.get('stage'),url=URL.createObjectURL(file);const empty=photos.find(p=>p.record===record&&p.stage===stage&&!p.url);if(empty)empty.url=url;else photos.push({id:Date.now()+i,record,stage,url,reviewed:false})});log('Photographs added',`${files.length} local image previews`);state.route='photos';state.photoFilter='All';state.query='';$('#search').value='';state.zone=0;toast('Local photo previews added.');},'Add to photo queue')}
function addIssue(){showDialog('Log an issue',`${select('record','Unit',records.map(r=>[r.id,`Blk ${r.block} · #${r.unit}`]),records[0].id)}${field('title','Issue title','','text','required maxlength="100"')}${field('owner','Responsible person / team','','text','required maxlength="80"')}<label class="field">Next action<textarea name="note" required maxlength="300"></textarea></label>`,f=>{issues.push({id:Date.now(),record:Number(f.get('record')),title:f.get('title').trim(),owner:f.get('owner').trim(),note:f.get('note').trim(),closed:false});log('Issue logged',f.get('title'));toast('Demo issue added.');})}
$('#modalForm').addEventListener('submit',e=>{e.preventDefault();try{submitAction?.(new FormData(e.target));$('#modal').close();render()}catch(err){$('#formError').textContent=err.message}});
$('#closeModal').onclick=$('#cancelModal').onclick=()=>$('#modal').close();$('#activityToggle').onclick=()=>$('#activity').classList.toggle('open');$('#closeActivity').onclick=()=>$('#activity').classList.remove('open');
$('#addAppointment').onclick=()=>{const n=nextFree();state.date=n.date;editRecord(null,n.slot,n.team)};$('#addPhotos').onclick=()=>uploadPhotos();$('#addIssue').onclick=addIssue;
$('#about').onclick=()=>showDialog('ELU Rehearsal · V9','<p class="dialog-note">Today Operations design checkpoint.<br><br>Creator / Admin: <b>manoharan varatharajan</b><br><br>Sample records only. This design rehearsal uses temporary in-memory changes; refresh restores the samples. Production data, login and database connections are separate.</p>',()=>{},'Got it');
$('#search').addEventListener('input',e=>{state.query=e.target.value;render()});document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!$('#modal').open){e.preventDefault();$('#search').focus()}});
function route(name){if(!navs.some(([id])=>id===name))name='today';state.route=name;history.replaceState(null,'','#'+name);$('#activity').classList.remove('open');render();window.scrollTo(0,0)}
document.addEventListener('change',e=>{if(e.target.id==='planDate'&&e.target.value){state.date=e.target.value;render()}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.route){route(b.dataset.route);return}
 if(b.dataset.zone!==undefined){state.zone=Number(b.dataset.zone);render();return}
 if(b.dataset.day){const d=new Date(state.date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+Number(b.dataset.day));state.date=d.toISOString().slice(0,10);render();return}
 if(b.dataset.edit){editRecord(Number(b.dataset.edit));return}
 if(b.dataset.unit){const r=records.find(x=>x.id===Number(b.dataset.unit));showDialog('Unit details',`<div class="unit-detail"><small>ZONE ${r.zone}</small><h3>Blk ${r.block} · #${esc(r.unit)}</h3><p><b>Owner / Resident</b><br>${esc(r.name)}</p><p><b>Contact</b><br>${esc(r.contact||'Not entered')}</p><p><b>Status</b><br>${badge(r)}</p><p><b>Appointment</b><br>${r.team?`${esc(r.date)} · ${slots[r.slot]} · Team ${r.team}`:'Not confirmed'}</p><p><b>Remarks</b><br>${esc(r.note)}</p></div>`,()=>{},'Close');return}
 if(b.dataset.newAppointment){const n=nextFree();state.date=n.date;editRecord(null,n.slot,n.team);return}
 if(b.dataset.newSlot!==undefined){editRecord(null,Number(b.dataset.newSlot),Number(b.dataset.team));return}
 if(b.dataset.newSurvey){editRecord(null,0,1,true);return}
 if(b.dataset.newIssue){addIssue();return}
 if(b.dataset.upload){uploadPhotos(Number(b.dataset.upload));return}
 if(b.dataset.photoFilter){state.photoFilter=b.dataset.photoFilter;render();return}
 if(b.dataset.review){const p=photos.find(p=>p.id===Number(b.dataset.review));p.reviewed=!p.reviewed;log(p.reviewed?'Photo reviewed':'Photo returned to queue','Local preview only');render();return}
 if(b.dataset.resolve){const i=issues.find(i=>i.id===Number(b.dataset.resolve));i.closed=!i.closed;log(i.closed?'Issue resolved':'Issue reopened',i.title);render();return}
 if(b.dataset.contact){const r=records.find(r=>r.id===Number(b.dataset.contact));showDialog(b.dataset.kind==='call'?'Call preview':'WhatsApp preview',`<p class="dialog-note"><b>Blk ${r.block} · #${esc(r.unit)}</b><br><br>${b.dataset.kind==='call'?'This sample record has no phone number. Calls will be available when real contact details are connected.':`Hi, your 10mm² sub-main cable upgrading appointment is scheduled for ${esc(r.date)}, ${slots[r.slot]}. Please confirm your availability.<br><br>This is a message preview. No WhatsApp message will be sent.`}</p>`,()=>{},'Close preview');return}
 if(b.dataset.print){window.print();return}
 if(b.dataset.export){const data=[['REHEARSAL SAMPLE DATA — NOT PRODUCTION'],['Block','Unit','Zone','Owner','Status','Date','Team','Time','Remarks'],...filtered().map(r=>[r.block,r.unit,r.zone,r.name,r.status,r.date,r.team||'',r.team?slots[r.slot]:'',r.note])];const csv=data.map(row=>row.map(v=>'"'+String(v).replace(/^[=+@-]/,m=>"'"+m).replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='ELU_Rehearsal_Sample_Report.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Sample report exported.');return}
});
window.addEventListener('hashchange',()=>route(location.hash.slice(1)));state.route=navs.some(([id])=>id===location.hash.slice(1))?location.hash.slice(1):'today';render();
if('serviceWorker' in navigator&&location.protocol!=='file:')window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
