'use strict';
const paths={today:'M3 5h18v16H3z M7 3v4 M17 3v4 M3 10h18 M7 14h3 M14 14h3 M7 18h3',units:'M4 3h16v18H4z M8 7h8 M8 12h8 M8 17h5',blocks:'M3 21V8h8v13 M11 21V3h10v18 M6 12h2 M6 16h2 M15 7h2 M15 11h2 M15 15h2 M2 21h20',survey:'M9 4H5v17h14V4h-4 M9 3h6v4H9z M8 14l3 3 5-6',photos:'M3 5h18v16H3z M3 17l5-5 4 4 3-3 6 6 M15 9h.01',issues:'M12 3L2 21h20z M12 9v5 M12 17h.01',reports:'M4 3h12l4 4v14H4z M8 16v-4 M12 16V9 M16 16v-6',bell:'M5 16h14l-2-3V9a5 5 0 0 0-10 0v4z M10 20h4',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14 M15 15l6 6',call:'M7 3H3c-1 10 8 19 18 18v-4l-5-2-2 2a15 15 0 0 1-7-7l2-2z',chat:'M21 11a9 9 0 0 1-13 8l-5 2 1-5A9 9 0 1 1 21 11 M8 10h8 M8 14h5',edit:'M14 5l5 5 M3 21l5-1L21 7l-4-4L4 16z',plus:'M12 5v14 M5 12h14',upload:'M12 16V3 M7 8l5-5 5 5 M3 16v5h18v-5',alert:'M12 3L2 21h20z M12 9v5 M12 17h.01'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.today}"/></svg>`;
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ranges=[[564,569],[544,550],[531,536],[557,562],[537,543],[551,556]],slots=['9am – 11am','11am – 1pm','2pm – 4pm','4pm – 6pm'],starts=['09:00','11:00','14:00','16:00'],ends=['11:00','13:00','16:00','18:00'];
const statusNames={A:'Completed',C:'Confirmed',D:'Opt-out',NR:'No response'};
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Singapore',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
let state={route:'today',zone:0,date:today,query:'',photoFilter:'All'};
let records=[
{id:1,block:531,unit:'05-322',name:'Sample resident 01',team:1,slot:0,status:'A',completed:today,note:'Inside / outside photos pending'},
{id:2,block:552,unit:'05-085',name:'Sample resident 02',team:2,slot:0,status:'A',completed:today,note:'Work completed · photo review'},
{id:3,block:544,unit:'02-114',name:'Sample resident 03',team:1,slot:1,status:'C',note:'Confirm access before arrival'},
{id:4,block:553,unit:'02-115',name:'Sample resident 04',team:2,slot:1,status:'C',note:'Owner available at the unit'},
{id:5,block:537,unit:'03-320',name:'Sample resident 05',team:1,slot:2,status:'C',note:'Check DB readiness'},
{id:6,block:557,unit:'10-117',name:'Sample resident 06',team:2,slot:2,status:'C',note:'Allow the full two-hour slot'},
{id:7,block:564,unit:'13-087',name:'Sample resident 07',team:1,slot:3,status:'C',note:'Long view photos required'},
{id:8,block:569,unit:'05-125',name:'Sample resident 08',team:2,slot:3,status:'C',note:'Call before arrival'},
{id:9,block:535,unit:'04-310',name:'Sample resident 09',team:null,slot:null,status:'NR',note:'Follow up with resident'},
{id:10,block:545,unit:'07-108',name:'Sample resident 10',team:null,slot:null,status:'D',note:'Collect signed opt-out form'}
].map(r=>({...r,date:today,contact:'',zone:ranges.findIndex(([a,b])=>r.block>=a&&r.block<=b)+1}));
let photos=[{id:1,record:1,stage:'After',url:'',reviewed:false},{id:2,record:2,stage:'Before',url:'',reviewed:false},{id:3,record:2,stage:'After',url:'',reviewed:false}];
let issues=[{id:1,record:5,title:'DB readiness check',note:'Confirm with the supervisor before sending the team.',owner:'Supervisor',closed:false},{id:2,record:1,title:'Completion photos pending',note:'Upload long view photographs inside and outside.',owner:'Team 1',closed:false}];
let events=[{time:'Sample activity',title:'Team 1 completed a unit',detail:'Blk 531 · #05-322 — photos pending'},{time:'Sample activity',title:'Team 2 work recorded',detail:'Blk 552 · #05-085 — ready for photo review'},{time:'Sample activity',title:'Afternoon appointments confirmed',detail:'Two teams · 2pm–4pm'}];
const navs=[['today','Today operations'],['photos','Photo queue'],['units','Unit register'],['blocks','Block board'],['survey','Survey visits'],['issues','Issues'],['reports','Meeting report']];
$('#navigation').innerHTML=navs.map(([id,title])=>`<button data-route="${id}" title="${title}" aria-label="${title}">${icon(id)}<span class="nav-label">${title}</span></button>`).join('');
$('#searchIcon').innerHTML=icon('search');$('#activityToggle').innerHTML=icon('bell');
$('#addAppointment').innerHTML=icon('plus')+'Appointment';$('#addPhotos').innerHTML=icon('upload')+'Photos';$('#addIssue').innerHTML=icon('issues')+'Issue';
const badge=r=>`<span class="status s-${r.status}">${r.status} · ${statusNames[r.status]}</span>`;
const filtered=()=>records.filter(r=>(!state.zone||r.zone===state.zone)&&`${r.block} ${r.unit} ${r.name} ${r.status}`.toLowerCase().includes(state.query.toLowerCase()));
const scheduled=()=>filtered().filter(r=>r.date===state.date&&r.team&&r.slot!==null&&['A','C'].includes(r.status));
const heading=(title,sub,action='')=>`<div class="page-head"><div><small class="eyebrow">PR3 / ${state.zone?'ZONE '+state.zone:'ALL SIX ZONES'}</small><h1>${title}</h1><p class="subtext">${sub}</p></div>${action}</div>`;
function render(){
 document.querySelectorAll('[data-route]').forEach(b=>{b.classList.toggle('active',b.dataset.route===state.route);b.setAttribute('aria-current',b.dataset.route===state.route?'page':'false')});
 $('#zones').innerHTML=`<button data-zone="0" class="${state.zone===0?'active':''}" aria-pressed="${state.zone===0}"><b>All zones</b><span>38 blocks</span></button>`+ranges.map(([a,b],i)=>`<button data-zone="${i+1}" class="${state.zone===i+1?'active':''}" aria-pressed="${state.zone===i+1}"><b>Zone ${i+1}</b><span>${a}–${b}</span></button>`).join('');
 const views={today:renderToday,photos:renderPhotos,units:renderUnits,blocks:renderBlocks,survey:renderSurvey,issues:renderIssues,reports:renderReports};$('#main').innerHTML=(views[state.route]||renderToday)();renderActivity();
}
function renderToday(){const jobs=scheduled();return heading('Today operations','A clear plan for the field. One slot, one team, one next action.',`<div class="date-control"><button data-day="-1" aria-label="Previous day">‹</button><input id="planDate" type="date" value="${state.date}" aria-label="Schedule date"><button data-day="1" aria-label="Next day">›</button></div>`)+`<div class="summaryline"><span><b>${jobs.length}</b> booked</span><span><b>${jobs.filter(r=>r.status==='A').length}</b> completed</span><span><b>${jobs.filter(r=>r.status==='C').length}</b> to visit</span><span class="legend"><span class="status s-A">A · Completed</span> <span class="status s-C">C · Confirmed</span></span></div><div class="timeline"><div class="team-head"><span>TIME / SGT</span>${[1,2].map(t=>`<div class="team-label"><span class="team-avatar ${t===2?'second':''}">T${t}</span><div><b>Team ${t}</b><small>Field appointments</small></div><span>${jobs.filter(r=>r.team===t).length} units</span></div>`).join('')}</div>${slots.map((s,i)=>`<div class="slot-row"><div class="slot-time">${starts[i]}<small>${ends[i]}</small><i></i></div>${[1,2].map(t=>{const r=jobs.find(r=>r.team===t&&r.slot===i);const occupied=records.some(r=>r.team===t&&r.slot===i&&r.date===state.date&&['A','C'].includes(r.status));return r?jobCard(r):`<div class="job empty">${occupied?'<span class="job-note">Outside current filter</span>':`<button data-new-slot="${i}" data-team="${t}">+ Available slot</button>`}</div>`}).join('')}</div>`).join('')}</div>`}
function jobCard(r){return `<article class="job ${r.status==='A'?'completed':''}"><div class="job-top"><span class="job-zone">ZONE ${r.zone} / ${r.status==='A'?'DONE':'VISIT'}</span>${badge(r)}</div><h3>Blk ${r.block} · #${esc(r.unit)}</h3><p class="job-person">${esc(r.name)}</p><div class="job-foot"><span class="job-note">${esc(r.note)}</span><div class="actions"><button class="round" data-contact="${r.id}" data-kind="call" aria-label="Call unit ${esc(r.unit)}" title="Call">${icon('call')}</button><button class="round" data-contact="${r.id}" data-kind="chat" aria-label="WhatsApp unit ${esc(r.unit)}" title="WhatsApp">${icon('chat')}</button><button class="round" data-edit="${r.id}" aria-label="Edit unit ${esc(r.unit)}" title="Edit appointment">${icon('edit')}</button></div></div></article>`}
function renderPhotos(){const ids=filtered().map(r=>r.id);const list=photos.filter(p=>ids.includes(p.record)&&(state.photoFilter==='All'||(state.photoFilter==='Reviewed'?p.reviewed:!p.reviewed)));return heading('Photo queue','Before, during and after. Review each unit’s evidence in one place.',`<button class="primary" data-upload="1">${icon('upload')} Add photos</button>`)+`<div class="toolbar"><div class="tabs">${['All','Needs review','Reviewed'].map(f=>`<button data-photo-filter="${f}" class="${state.photoFilter===f?'active':''}">${f}</button>`).join('')}</div><span class="subtext">${list.length} photo items · previews stay in this tab</span></div><div class="photo-queue">${list.map(p=>{const r=records.find(r=>r.id===p.record);return `<article class="photo-tile"><div class="photo-image">${p.url?`<img src="${p.url}" alt="${esc(p.stage)} photo for block ${r.block}, unit ${esc(r.unit)}">`:icon('photos')}</div><div class="photo-info"><div class="photo-stage">${esc(p.stage)} / ${p.url?'Local preview':'Awaiting upload'}</div><h3>Blk ${r.block} · #${esc(r.unit)}</h3><p>${p.reviewed?'Reviewed in rehearsal':p.url?'Ready for visual review':'No site photograph attached'}</p><button class="secondary" ${p.url?`data-review="${p.id}"`:`data-upload="${r.id}"`}>${p.url?(p.reviewed?'Return to queue':'Mark reviewed'):'Attach photograph'} ↗</button></div></article>`}).join('')||'<div class="empty-state">No photos match this filter.</div>'}</div>`}
function renderUnits(){const rows=filtered();return heading('Unit register','Owner and appointment details from the same demo records. Read-only view.')+`<div class="toolbar">${Object.keys(statusNames).map(s=>`<span class="status s-${s}">${s} · ${statusNames[s]}</span>`).join('')}</div><div class="table-wrap"><table><thead><tr><th>BLOCK / UNIT</th><th>ZONE</th><th>OWNER / RESIDENT</th><th>STATUS</th><th>APPOINTMENT</th><th>REMARKS</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${r.block} · #${esc(r.unit)}</b></td><td>${r.zone}</td><td>${esc(r.name)}</td><td>${badge(r)}</td><td>${r.team?`${esc(r.date)}<br>${slots[r.slot]} · Team ${r.team}`:'—'}</td><td>${esc(r.note)}</td></tr>`).join('')||'<tr><td colspan="6">No matching units.</td></tr>'}</tbody></table></div>`}
function renderBlocks(){const rows=filtered();const zones=state.zone?[state.zone]:[1,2,3,4,5,6];return heading('Block board','Select a unit tile to inspect its appointment and status.')+`<div class="toolbar">${Object.keys(statusNames).map(s=>`<span class="status s-${s}">${s} · ${statusNames[s]}</span>`).join('')}</div><div class="blocklist">${zones.flatMap(z=>{const [a,b]=ranges[z-1];return Array.from({length:b-a+1},(_,i)=>a+i).filter(block=>!state.query||rows.some(r=>r.block===block)).map(block=>`<div class="blockrow"><h3>Blk ${block}<small>Zone ${z}</small></h3>${rows.filter(r=>r.block===block).map(r=>`<button class="unit-tile s-${r.status}" data-edit="${r.id}"><b>#${esc(r.unit)}</b>${r.status} · ${statusNames[r.status]}</button>`).join('')||'<span class="subtext">No sample units entered</span>'}</div>`)}).join('')||'<div class="empty-state">No matching blocks.</div>'}</div>`}
function renderSurvey(){return heading('Survey visits','One record per unit. Owner details flow into the unit register.',`<button class="primary" data-new-survey="1">+ Add survey unit</button>`)+`<div class="issue-list">${filtered().map(r=>`<article class="issue"><div><small class="eyebrow">ZONE ${r.zone} · ${r.status}</small><h3>Blk ${r.block} · #${esc(r.unit)}</h3><p>${esc(r.name)}<br>${esc(r.note)}</p></div><button class="secondary" data-edit="${r.id}">Edit record ↗</button></article>`).join('')||'<div class="empty-state">No survey records match this filter.</div>'}</div>`}
function renderIssues(){const ids=filtered().map(r=>r.id);return heading('Issues & follow-ups','Keep the next action and its owner visible.',`<button class="primary" data-new-issue="1">+ Log issue</button>`)+`<div class="issue-list">${issues.filter(i=>ids.includes(i.record)).map(i=>{const r=records.find(r=>r.id===i.record);return `<article class="issue ${i.closed?'closed':''}"><div><small class="eyebrow">${i.closed?'RESOLVED':'OPEN'} / ${esc(i.owner)}</small><h3>${esc(i.title)}</h3><p>Blk ${r.block} · #${esc(r.unit)}<br>${esc(i.note)}</p></div><button class="secondary" data-resolve="${i.id}">${i.closed?'Reopen':'Mark resolved'}</button></article>`}).join('')||'<div class="empty-state">No issues match this filter.</div>'}</div>`}
function renderReports(){const rows=filtered();return heading('Meeting brief','A sample-record summary for design review. No production figures.',`<button class="secondary" data-export="1">Export CSV ↗</button>`)+`<div class="report"><h2>Status by zone</h2><div class="table-wrap"><table><thead><tr><th>ZONE / BLOCKS</th><th>SAMPLE UNITS</th><th>A</th><th>C</th><th>D</th><th>NR</th></tr></thead><tbody>${ranges.map(([a,b],i)=>{const rr=rows.filter(r=>r.zone===i+1);return (!state.zone||state.zone===i+1)?`<tr><td><b>Zone ${i+1}</b> · ${a}–${b}</td><td>${rr.length}</td>${['A','C','D','NR'].map(s=>`<td>${rr.filter(r=>r.status===s).length}</td>`).join('')}</tr>`:''}).join('')}</tbody></table></div><p class="subtext">Counts include only sample units entered in this rehearsal, filtered by the selected zone and search. This is not overall project completion.</p><div class="toolbar" style="margin-top:24px"><button class="secondary" data-print="1">Print meeting brief</button></div></div>`}
function renderActivity(){const open=issues.filter(i=>!i.closed);$('#activityContent').innerHTML=(open.length?`<div class="alert-box"><div class="alert-top">${icon('alert')} ${open.length} items need attention</div><p>${esc(open[0].title)}<br>${esc(open[0].note)}</p><button class="text-action" data-route="issues">Review follow-ups ↗</button></div>`:'<div class="alert-box"><p>No open follow-ups.</p></div>')+`<div class="feed-label"><b>Workspace activity</b><span>This session</span></div><div class="feed">${events.slice(0,10).map(e=>`<div class="event"><time>${esc(e.time)}</time><p>${esc(e.title)}</p><span>${esc(e.detail)}</span></div>`).join('')}</div>`}
function log(title,detail){events.unshift({time:new Intl.DateTimeFormat('en-SG',{timeZone:'Asia/Singapore',hour:'2-digit',minute:'2-digit'}).format(new Date()),title,detail})}
let toastTimer;function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
let submitAction=null;function showDialog(title,html,fn,button='Save demo change'){submitAction=fn;$('#modalTitle').textContent=title;$('#modalFields').innerHTML=html+'<p id="formError" class="dialog-error" role="alert"></p>';$('#saveModal').textContent=button;$('#cancelModal').textContent='Cancel';$('#modal').showModal()}
const field=(name,label,value='',type='text',extra='')=>`<label class="field">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const select=(name,label,options,value)=>`<label class="field">${label}<select name="${name}">${options.map(([v,t])=>`<option value="${v}" ${String(v)===String(value)?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;
function editRecord(id=null,slot=0,team=1,survey=false){const r=records.find(r=>r.id===id)||{block:state.zone?ranges[state.zone-1][0]:531,unit:'',name:'',status:survey?'NR':'C',date:state.date,team:survey?'':team,slot,note:'',completed:''};showDialog(id?'Edit unit & appointment':survey?'Add survey unit':'New appointment',`<p class="dialog-note">Rehearsal only. Saved changes update all views in this tab.</p><div class="form-row">${field('block','Block',r.block,'number','required min="531" max="569"')}${field('unit','Unit (e.g. 05-322)',r.unit,'text','required pattern="[0-9]{2}-[0-9]{2,4}"')}</div>${field('name','Owner / resident',r.name,'text','required maxlength="80"')}<div class="form-row">${select('status','Status',Object.entries(statusNames).map(([s,n])=>[s,`${s} — ${n}`]),r.status)}${field('date','Appointment date',r.date,'date','required')}</div><div class="form-row">${select('team','Team',[['','Unassigned'],[1,'Team 1'],[2,'Team 2']],r.team??'')}${select('slot','Time slot',slots.map((s,i)=>[i,s]),r.slot??0)}</div>${field('completed','Completion date (required for A)',r.completed||'','date')}<label class="field">Remarks<textarea name="note" maxlength="250">${esc(r.note)}</textarea></label>`,f=>{
 const block=Number(f.get('block')),unit=f.get('unit').trim(),zone=ranges.findIndex(([a,b])=>block>=a&&block<=b)+1,status=f.get('status'),newTeam=f.get('team')?Number(f.get('team')):null,newSlot=Number(f.get('slot'));
 if(!zone)throw Error('Choose a block within the six project zones.');if(records.some(x=>x.id!==id&&x.block===block&&x.unit===unit))throw Error('This unit already exists. Edit the existing record.');
 if(status==='A'&&!f.get('completed'))throw Error('Add a completion date before saving status A.');
 if(status==='C'&&!newTeam)throw Error('Choose a team for a confirmed appointment.');
 if(newTeam&&['A','C'].includes(status)&&records.some(x=>x.id!==id&&x.team===newTeam&&x.slot===newSlot&&x.date===f.get('date')&&['A','C'].includes(x.status)))throw Error('This team already has a unit in that slot. Choose another slot or team.');
 const updated={...r,id:id||Date.now(),block,unit,zone,name:f.get('name').trim(),status,date:f.get('date'),team:['A','C'].includes(status)?newTeam:null,slot:['A','C'].includes(status)?newSlot:null,completed:status==='A'?f.get('completed'):'',note:f.get('note').trim()};
 if(id)records=records.map(x=>x.id===id?updated:x);else records.push(updated);log(id?'Unit record updated':'New unit added',`Blk ${block} · #${unit} — ${status}`);toast('Demo record saved across all views.');
 })}
function uploadPhotos(recordId){showDialog('Add site photographs',`<p class="dialog-note">Images preview locally in this tab. They are not uploaded to a server and disappear on refresh.</p>${select('record','Unit',records.map(r=>[r.id,`Blk ${r.block} · #${r.unit}`]),recordId||records[0].id)}${select('stage','Work stage',[['Before','Before'],['During','During'],['After','After']],'After')}${field('files','Select photographs','','file','required accept="image/*" multiple')}`,f=>{const files=[...$('#modalFields input[type=file]').files];if(files.some(file=>!file.type.startsWith('image/')))throw Error('Choose image files only.');files.forEach((file,i)=>{const record=Number(f.get('record')),stage=f.get('stage'),url=URL.createObjectURL(file);const empty=photos.find(p=>p.record===record&&p.stage===stage&&!p.url);if(empty)empty.url=url;else photos.push({id:Date.now()+i,record,stage,url,reviewed:false})});log('Photographs added',`${files.length} local image previews`);state.route='photos';state.photoFilter='All';state.query='';$('#search').value='';state.zone=0;toast('Local photo previews added.');},'Add to photo queue')}
function addIssue(){showDialog('Log an issue',`${select('record','Unit',records.map(r=>[r.id,`Blk ${r.block} · #${r.unit}`]),records[0].id)}${field('title','Issue title','','text','required maxlength="100"')}${field('owner','Responsible person / team','','text','required maxlength="80"')}<label class="field">Next action<textarea name="note" required maxlength="300"></textarea></label>`,f=>{issues.push({id:Date.now(),record:Number(f.get('record')),title:f.get('title').trim(),owner:f.get('owner').trim(),note:f.get('note').trim(),closed:false});log('Issue logged',f.get('title'));toast('Demo issue added.');})}
$('#modalForm').addEventListener('submit',e=>{e.preventDefault();try{submitAction?.(new FormData(e.target));$('#modal').close();render()}catch(err){$('#formError').textContent=err.message}});
$('#closeModal').onclick=$('#cancelModal').onclick=()=>$('#modal').close();$('#activityToggle').onclick=()=>$('#activity').classList.toggle('open');$('#closeActivity').onclick=()=>$('#activity').classList.remove('open');
$('#addAppointment').onclick=()=>editRecord();$('#addPhotos').onclick=()=>uploadPhotos();$('#addIssue').onclick=addIssue;
$('#about').onclick=()=>showDialog('ELU Rehearsal · V7','<p class="dialog-note">Today Operations design checkpoint.<br><br>Creator / Admin: <b>manoharan varatharajan</b><br><br>Sample records only. This design rehearsal uses temporary in-memory changes; refresh restores the samples. Production data, login and database connections are separate.</p>',()=>{},'Got it');
$('#search').addEventListener('input',e=>{state.query=e.target.value;render()});document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!$('#modal').open){e.preventDefault();$('#search').focus()}});
function route(name){if(!navs.some(([id])=>id===name))name='today';state.route=name;history.replaceState(null,'','#'+name);$('#activity').classList.remove('open');render();window.scrollTo(0,0)}
document.addEventListener('change',e=>{if(e.target.id==='planDate'&&e.target.value){state.date=e.target.value;render()}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.route){route(b.dataset.route);return}
 if(b.dataset.zone!==undefined){state.zone=Number(b.dataset.zone);render();return}
 if(b.dataset.day){const d=new Date(state.date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+Number(b.dataset.day));state.date=d.toISOString().slice(0,10);render();return}
 if(b.dataset.edit){editRecord(Number(b.dataset.edit));return}
 if(b.dataset.newSlot!==undefined){editRecord(null,Number(b.dataset.newSlot),Number(b.dataset.team));return}
 if(b.dataset.newSurvey){editRecord(null,0,1,true);return}
 if(b.dataset.newIssue){addIssue();return}
 if(b.dataset.upload){uploadPhotos(Number(b.dataset.upload));return}
 if(b.dataset.photoFilter){state.photoFilter=b.dataset.photoFilter;render();return}
 if(b.dataset.review){const p=photos.find(p=>p.id===Number(b.dataset.review));p.reviewed=!p.reviewed;log(p.reviewed?'Photo reviewed':'Photo returned to queue','Local preview only');render();return}
 if(b.dataset.resolve){const i=issues.find(i=>i.id===Number(b.dataset.resolve));i.closed=!i.closed;log(i.closed?'Issue resolved':'Issue reopened',i.title);render();return}
 if(b.dataset.contact){const r=records.find(r=>r.id===Number(b.dataset.contact));showDialog(b.dataset.kind==='call'?'Call preview':'WhatsApp preview',`<p class="dialog-note"><b>Blk ${r.block} · #${esc(r.unit)}</b><br><br>${b.dataset.kind==='call'?'This sample record has no phone number. Calls will be available when real contact details are connected.':`Hi, your 10mm² sub-main cable upgrading appointment is scheduled for ${esc(r.date)}, ${slots[r.slot]}. Please confirm your availability.<br><br>This is a message preview. No WhatsApp message will be sent.`}</p>`,()=>{},'Close preview');return}
 if(b.dataset.print){window.print();return}
 if(b.dataset.export){const data=[['REHEARSAL SAMPLE DATA — NOT PRODUCTION'],['Block','Unit','Zone','Owner','Status','Date','Team','Time','Remarks'],...filtered().map(r=>[r.block,r.unit,r.zone,r.name,r.status,r.date,r.team||'',r.team?slots[r.slot]:'',r.note])];const csv=data.map(row=>row.map(v=>'"'+String(v).replace(/^[=+@-]/,m=>"'"+m).replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='ELU_Rehearsal_Sample_Report.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Sample report exported.');return}
});
window.addEventListener('hashchange',()=>route(location.hash.slice(1)));state.route=navs.some(([id])=>id===location.hash.slice(1))?location.hash.slice(1):'today';render();
if('serviceWorker' in navigator&&location.protocol!=='file:')window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
